env: inverted_double_pendulum
control_dt: 0.005
task_time: 10.0
seed: 12345678

safety_alpha: 1.0
safety_margin: 0.0

num_eval: 20
evaluation_period: 30000
grad_step_max: 2000000
grad_clip: 3.0
replay_warmup_size: 20000

sf:
  lambda_init_scale: 0.1
  lambda_final_scale: 0.0001
  lambda_increasing_interval: 1000000
  lambda_start_to_decrease: 50000
  lr_decreasing_interval: 500000
  warmup_steps: 5000
  tau: 0.005
  with_warm_up: true

  lr_safe_value: 0.0003
  lr_safe_q_coeff: 0.0005
  lr_safe_q_scalar: 0.0003
  lr_safe_value_goal: 0.000001
  lr_safe_q_coeff_goal: 0.000002
  lr_safe_q_scalar_goal: 0.000001

  batch_size: 256
  hidden_size: 256
  hidden_layers: 2
  target_update_interval: 1
  replay_size: 2000000